include classpath("application.conf")

node-address {
    protocol = http
    host = "*"
    port = 9324
    context-path = ""
}

rest-sqs {
    enabled = true
    bind-port = 9324
    bind-hostname = "0.0.0.0"
    sqs-limits = relaxed
}

queues {
    example-queue {
        defaultVisibilityTimeout = 10 seconds
        delay = 5 seconds
        receiveMessageWait = 0 seconds
        deadLettersQueue {
            name = "example-queue_DLQ"
            maxReceiveCount = 5
        }
        fifo = false
        contentBasedDeduplication = false
    }

    example-queue_DLQ {
        defaultVisibilityTimeout = 10 seconds
        delay = 5 seconds
        receiveMessageWait = 0 seconds
        fifo = false
        contentBasedDeduplication = false
    }
}

aws {
  region = eu-central-1
  accountId = 000000000000
}